pipeline {
    
    agent {
    docker { image 'python' }
  } 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git url: 'https://github.com/Atharva-Thakur/Jenkins',
                branch: 'main'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    cd python-jenkins-argocd-k8s
                    echo 'Build Docker Image'
                    docker build -t atharvarthakur/cicd-e2e:${BUILD_NUMBER} .
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    withCredentials([usernamePassword(credentialsId: 'atharvarthakur-dockerhub', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                        sh '''
                        echo 'Push to Repo'
                        docker login -u $USERNAME -p $PASSWORD
                        docker push atharvarthakur/cicd-e2e:${BUILD_NUMBER}
                        '''
                    }
                }
            }
        }
    }
}
